= README

:github: https://github.com/opitzconsulting/remix-blog
:blog: https://thecattlecrew.net

This repository contains the source code for the blog post {blog}["Remix—Ein leichtgewichtiger Ansatz für Geschäftsanwendungen"].

== Prerequisites

* Docker
* Node.js (>= 20)
* yarn

== Getting Started development

After cloning the project, start the postgres container using docker in the root directory of the project.


== Configuring .env

An env.sample is provided in the project rot directory.
Copy the file to .env.

[source, bash]
----
cp env.sample .env
----

And for simplicity reason link to this one from the chinook directory.

[source, bash]
----
cd chinook
ln -s ../.env .env
----

== Starting infractructure (Postgres / Keycloak)

[source, bash]
----
docker compose --profile default --profile authn up -d
----

Then install the dependencies and start the application (in the chinook subdirectory)

[source, bash]
----
yarn install
yarn dev
----

The application is now available at http://localhost:5173.

== Database Access

Two users are create for the chinook database:

* chinook_admin / chinook_admin
* chinook_user / chinook_user


== Generating types from DB tables

To generate types from the database tables, run the following command in the chinook directory:

[source, bash]
----
yarn kysely-generate
----



